<?php
/**
 * Invitation
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Libre Graph API
 *
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * Invitation Class Doc Comment
 *
 * @description Represents an invitation to a drive item.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class Invitation implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'invitation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'invited_user_display_name' => 'string',
        'invited_user_email_address' => 'string',
        'invited_user_message_info' => '\OpenAPI\Client\Model\InvitedUserMessageInfo',
        'send_invitation_message' => 'bool',
        'invite_redirect_url' => 'string',
        'invite_redeem_url' => 'string',
        'status' => 'string',
        'invited_user' => '\OpenAPI\Client\Model\User',
        'invited_user_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'invited_user_display_name' => null,
        'invited_user_email_address' => null,
        'invited_user_message_info' => null,
        'send_invitation_message' => null,
        'invite_redirect_url' => null,
        'invite_redeem_url' => null,
        'status' => null,
        'invited_user' => null,
        'invited_user_type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'invited_user_display_name' => false,
        'invited_user_email_address' => false,
        'invited_user_message_info' => false,
        'send_invitation_message' => false,
        'invite_redirect_url' => false,
        'invite_redeem_url' => false,
        'status' => false,
        'invited_user' => false,
        'invited_user_type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'invited_user_display_name' => 'invitedUserDisplayName',
        'invited_user_email_address' => 'invitedUserEmailAddress',
        'invited_user_message_info' => 'invitedUserMessageInfo',
        'send_invitation_message' => 'sendInvitationMessage',
        'invite_redirect_url' => 'inviteRedirectUrl',
        'invite_redeem_url' => 'inviteRedeemUrl',
        'status' => 'status',
        'invited_user' => 'invitedUser',
        'invited_user_type' => 'invitedUserType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'invited_user_display_name' => 'setInvitedUserDisplayName',
        'invited_user_email_address' => 'setInvitedUserEmailAddress',
        'invited_user_message_info' => 'setInvitedUserMessageInfo',
        'send_invitation_message' => 'setSendInvitationMessage',
        'invite_redirect_url' => 'setInviteRedirectUrl',
        'invite_redeem_url' => 'setInviteRedeemUrl',
        'status' => 'setStatus',
        'invited_user' => 'setInvitedUser',
        'invited_user_type' => 'setInvitedUserType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'invited_user_display_name' => 'getInvitedUserDisplayName',
        'invited_user_email_address' => 'getInvitedUserEmailAddress',
        'invited_user_message_info' => 'getInvitedUserMessageInfo',
        'send_invitation_message' => 'getSendInvitationMessage',
        'invite_redirect_url' => 'getInviteRedirectUrl',
        'invite_redeem_url' => 'getInviteRedeemUrl',
        'status' => 'getStatus',
        'invited_user' => 'getInvitedUser',
        'invited_user_type' => 'getInvitedUserType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('invited_user_display_name', $data ?? [], null);
        $this->setIfExists('invited_user_email_address', $data ?? [], null);
        $this->setIfExists('invited_user_message_info', $data ?? [], null);
        $this->setIfExists('send_invitation_message', $data ?? [], null);
        $this->setIfExists('invite_redirect_url', $data ?? [], null);
        $this->setIfExists('invite_redeem_url', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('invited_user', $data ?? [], null);
        $this->setIfExists('invited_user_type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets invited_user_display_name
     *
     * @return string|null
     */
    public function getInvitedUserDisplayName(): ?string
    {
        return $this->container['invited_user_display_name'];
    }

    /**
     * Sets invited_user_display_name
     *
     * @param string|null $invited_user_display_name The display name of the user being invited.
     *
     * @return $this
     */
    public function setInvitedUserDisplayName(?string $invited_user_display_name): static
    {
        if (is_null($invited_user_display_name)) {
            throw new InvalidArgumentException('non-nullable invited_user_display_name cannot be null');
        }
        $this->container['invited_user_display_name'] = $invited_user_display_name;

        return $this;
    }

    /**
     * Gets invited_user_email_address
     *
     * @return string|null
     */
    public function getInvitedUserEmailAddress(): ?string
    {
        return $this->container['invited_user_email_address'];
    }

    /**
     * Sets invited_user_email_address
     *
     * @param string|null $invited_user_email_address The email address of the user being invited. Required.
     *
     * @return $this
     */
    public function setInvitedUserEmailAddress(?string $invited_user_email_address): static
    {
        if (is_null($invited_user_email_address)) {
            throw new InvalidArgumentException('non-nullable invited_user_email_address cannot be null');
        }
        $this->container['invited_user_email_address'] = $invited_user_email_address;

        return $this;
    }

    /**
     * Gets invited_user_message_info
     *
     * @return \OpenAPI\Client\Model\InvitedUserMessageInfo|null
     */
    public function getInvitedUserMessageInfo(): ?\OpenAPI\Client\Model\InvitedUserMessageInfo
    {
        return $this->container['invited_user_message_info'];
    }

    /**
     * Sets invited_user_message_info
     *
     * @param \OpenAPI\Client\Model\InvitedUserMessageInfo|null $invited_user_message_info invited_user_message_info
     *
     * @return $this
     */
    public function setInvitedUserMessageInfo(?\OpenAPI\Client\Model\InvitedUserMessageInfo $invited_user_message_info): static
    {
        if (is_null($invited_user_message_info)) {
            throw new InvalidArgumentException('non-nullable invited_user_message_info cannot be null');
        }
        $this->container['invited_user_message_info'] = $invited_user_message_info;

        return $this;
    }

    /**
     * Gets send_invitation_message
     *
     * @return bool|null
     */
    public function getSendInvitationMessage(): ?bool
    {
        return $this->container['send_invitation_message'];
    }

    /**
     * Sets send_invitation_message
     *
     * @param bool|null $send_invitation_message Indicates whether an invitation message should be sent to the user.
     *
     * @return $this
     */
    public function setSendInvitationMessage(?bool $send_invitation_message): static
    {
        if (is_null($send_invitation_message)) {
            throw new InvalidArgumentException('non-nullable send_invitation_message cannot be null');
        }
        $this->container['send_invitation_message'] = $send_invitation_message;

        return $this;
    }

    /**
     * Gets invite_redirect_url
     *
     * @return string|null
     */
    public function getInviteRedirectUrl(): ?string
    {
        return $this->container['invite_redirect_url'];
    }

    /**
     * Sets invite_redirect_url
     *
     * @param string|null $invite_redirect_url The URL to which the user is redirected after accepting the invitation. Required.
     *
     * @return $this
     */
    public function setInviteRedirectUrl(?string $invite_redirect_url): static
    {
        if (is_null($invite_redirect_url)) {
            throw new InvalidArgumentException('non-nullable invite_redirect_url cannot be null');
        }
        $this->container['invite_redirect_url'] = $invite_redirect_url;

        return $this;
    }

    /**
     * Gets invite_redeem_url
     *
     * @return string|null
     */
    public function getInviteRedeemUrl(): ?string
    {
        return $this->container['invite_redeem_url'];
    }

    /**
     * Sets invite_redeem_url
     *
     * @param string|null $invite_redeem_url The URL that the user can use to redeem the invitation. Read-only.
     *
     * @return $this
     */
    public function setInviteRedeemUrl(?string $invite_redeem_url): static
    {
        if (is_null($invite_redeem_url)) {
            throw new InvalidArgumentException('non-nullable invite_redeem_url cannot be null');
        }
        $this->container['invite_redeem_url'] = $invite_redeem_url;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The status of the invitation. Read-only.
     *
     * @return $this
     */
    public function setStatus(?string $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets invited_user
     *
     * @return \OpenAPI\Client\Model\User|null
     */
    public function getInvitedUser(): ?\OpenAPI\Client\Model\User
    {
        return $this->container['invited_user'];
    }

    /**
     * Sets invited_user
     *
     * @param \OpenAPI\Client\Model\User|null $invited_user invited_user
     *
     * @return $this
     */
    public function setInvitedUser(?\OpenAPI\Client\Model\User $invited_user): static
    {
        if (is_null($invited_user)) {
            throw new InvalidArgumentException('non-nullable invited_user cannot be null');
        }
        $this->container['invited_user'] = $invited_user;

        return $this;
    }

    /**
     * Gets invited_user_type
     *
     * @return string|null
     */
    public function getInvitedUserType(): ?string
    {
        return $this->container['invited_user_type'];
    }

    /**
     * Sets invited_user_type
     *
     * @param string|null $invited_user_type The type of user being invited.
     *
     * @return $this
     */
    public function setInvitedUserType(?string $invited_user_type): static
    {
        if (is_null($invited_user_type)) {
            throw new InvalidArgumentException('non-nullable invited_user_type cannot be null');
        }
        $this->container['invited_user_type'] = $invited_user_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


