<?php
/**
 * LockInfo
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Libre Graph API
 *
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * LockInfo Class Doc Comment
 *
 * @description Read-only lock metadata for a file, matching the MS Graph beta lockInfo resource. Indicates whether the file is locked, the kind of lock, when it was created, when it expires and who holds it.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class LockInfo implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'lockInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'lock_type' => 'string',
        'created_date_time' => '\DateTime',
        'expiration_date_time' => '\DateTime',
        'owners' => '\OpenAPI\Client\Model\Identity[]',
        'at_libre_graph_app_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'lock_type' => null,
        'created_date_time' => 'date-time',
        'expiration_date_time' => 'date-time',
        'owners' => null,
        'at_libre_graph_app_name' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'lock_type' => false,
        'created_date_time' => false,
        'expiration_date_time' => false,
        'owners' => false,
        'at_libre_graph_app_name' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'lock_type' => 'lockType',
        'created_date_time' => 'createdDateTime',
        'expiration_date_time' => 'expirationDateTime',
        'owners' => 'owners',
        'at_libre_graph_app_name' => '@libre.graph.appName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'lock_type' => 'setLockType',
        'created_date_time' => 'setCreatedDateTime',
        'expiration_date_time' => 'setExpirationDateTime',
        'owners' => 'setOwners',
        'at_libre_graph_app_name' => 'setAtLibreGraphAppName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'lock_type' => 'getLockType',
        'created_date_time' => 'getCreatedDateTime',
        'expiration_date_time' => 'getExpirationDateTime',
        'owners' => 'getOwners',
        'at_libre_graph_app_name' => 'getAtLibreGraphAppName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const LOCK_TYPE_NONE = 'none';
    public const LOCK_TYPE_EXCLUSIVE = 'exclusive';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getLockTypeAllowableValues()
    {
        return [
            self::LOCK_TYPE_NONE,
            self::LOCK_TYPE_EXCLUSIVE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('lock_type', $data ?? [], null);
        $this->setIfExists('created_date_time', $data ?? [], null);
        $this->setIfExists('expiration_date_time', $data ?? [], null);
        $this->setIfExists('owners', $data ?? [], null);
        $this->setIfExists('at_libre_graph_app_name', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        $allowedValues = $this->getLockTypeAllowableValues();
        if (!is_null($this->container['lock_type']) && !in_array($this->container['lock_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'lock_type', must be one of '%s'",
                $this->container['lock_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets lock_type
     *
     * @return string|null
     */
    public function getLockType(): ?string
    {
        return $this->container['lock_type'];
    }

    /**
     * Sets lock_type
     *
     * @param string|null $lock_type The type of lock currently held on the file. OpenCloud currently only issues exclusive locks, same as MS Graph, even if it defines more. Read-only.
     *
     * @return $this
     */
    public function setLockType(?string $lock_type): static
    {
        if (is_null($lock_type)) {
            throw new InvalidArgumentException('non-nullable lock_type cannot be null');
        }
        $allowedValues = $this->getLockTypeAllowableValues();
        if (!in_array($lock_type, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'lock_type', must be one of '%s'",
                    $lock_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['lock_type'] = $lock_type;

        return $this;
    }

    /**
     * Gets created_date_time
     *
     * @return \DateTime|null
     */
    public function getCreatedDateTime(): ?\DateTime
    {
        return $this->container['created_date_time'];
    }

    /**
     * Sets created_date_time
     *
     * @param \DateTime|null $created_date_time The date and time when the lock was created, in UTC. Read-only.
     *
     * @return $this
     */
    public function setCreatedDateTime(?\DateTime $created_date_time): static
    {
        if (is_null($created_date_time)) {
            throw new InvalidArgumentException('non-nullable created_date_time cannot be null');
        }
        $this->container['created_date_time'] = $created_date_time;

        return $this;
    }

    /**
     * Gets expiration_date_time
     *
     * @return \DateTime|null
     */
    public function getExpirationDateTime(): ?\DateTime
    {
        return $this->container['expiration_date_time'];
    }

    /**
     * Sets expiration_date_time
     *
     * @param \DateTime|null $expiration_date_time The date and time when the lock expires, in UTC. Read-only.
     *
     * @return $this
     */
    public function setExpirationDateTime(?\DateTime $expiration_date_time): static
    {
        if (is_null($expiration_date_time)) {
            throw new InvalidArgumentException('non-nullable expiration_date_time cannot be null');
        }
        $this->container['expiration_date_time'] = $expiration_date_time;

        return $this;
    }

    /**
     * Gets owners
     *
     * @return \OpenAPI\Client\Model\Identity[]|null
     */
    public function getOwners(): ?array
    {
        return $this->container['owners'];
    }

    /**
     * Sets owners
     *
     * @param \OpenAPI\Client\Model\Identity[]|null $owners The collection of users that currently hold the lock on the file. Read-only.
     *
     * @return $this
     */
    public function setOwners(?array $owners): static
    {
        if (is_null($owners)) {
            throw new InvalidArgumentException('non-nullable owners cannot be null');
        }
        $this->container['owners'] = $owners;

        return $this;
    }

    /**
     * Gets at_libre_graph_app_name
     *
     * @return string|null
     */
    public function getAtLibreGraphAppName(): ?string
    {
        return $this->container['at_libre_graph_app_name'];
    }

    /**
     * Sets at_libre_graph_app_name
     *
     * @param string|null $at_libre_graph_app_name Name of the application holding the lock, for example an office application. Not part of MS Graph. Read-only.
     *
     * @return $this
     */
    public function setAtLibreGraphAppName(?string $at_libre_graph_app_name): static
    {
        if (is_null($at_libre_graph_app_name)) {
            throw new InvalidArgumentException('non-nullable at_libre_graph_app_name cannot be null');
        }
        $this->container['at_libre_graph_app_name'] = $at_libre_graph_app_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


