<?php
/**
 * SearchRequest
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Libre Graph API
 *
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * SearchRequest Class Doc Comment
 *
 * @description Represents an individual search request within a search query. Follows the [MS Graph searchRequest](https://learn.microsoft.com/en-us/graph/api/resources/searchrequest) resource type.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class SearchRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'searchRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'entity_types' => 'string[]',
        'query' => '\OpenAPI\Client\Model\SearchQuery',
        'from' => 'int',
        'size' => 'int',
        'aggregations' => '\OpenAPI\Client\Model\AggregationOption[]',
        'aggregation_filters' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'entity_types' => null,
        'query' => null,
        'from' => 'int32',
        'size' => 'int32',
        'aggregations' => null,
        'aggregation_filters' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'entity_types' => false,
        'query' => false,
        'from' => false,
        'size' => false,
        'aggregations' => false,
        'aggregation_filters' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'entity_types' => 'entityTypes',
        'query' => 'query',
        'from' => 'from',
        'size' => 'size',
        'aggregations' => 'aggregations',
        'aggregation_filters' => 'aggregationFilters'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'entity_types' => 'setEntityTypes',
        'query' => 'setQuery',
        'from' => 'setFrom',
        'size' => 'setSize',
        'aggregations' => 'setAggregations',
        'aggregation_filters' => 'setAggregationFilters'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'entity_types' => 'getEntityTypes',
        'query' => 'getQuery',
        'from' => 'getFrom',
        'size' => 'getSize',
        'aggregations' => 'getAggregations',
        'aggregation_filters' => 'getAggregationFilters'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const ENTITY_TYPES_DRIVE_ITEM = 'driveItem';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getEntityTypesAllowableValues()
    {
        return [
            self::ENTITY_TYPES_DRIVE_ITEM,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('entity_types', $data ?? [], null);
        $this->setIfExists('query', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], 0);
        $this->setIfExists('size', $data ?? [], 25);
        $this->setIfExists('aggregations', $data ?? [], null);
        $this->setIfExists('aggregation_filters', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['entity_types'] === null) {
            $invalidProperties[] = "'entity_types' can't be null";
        }
        if ((count($this->container['entity_types']) < 1)) {
            $invalidProperties[] = "invalid value for 'entity_types', number of items must be greater than or equal to 1.";
        }

        if ($this->container['query'] === null) {
            $invalidProperties[] = "'query' can't be null";
        }
        if (!is_null($this->container['from']) && ($this->container['from'] < 0)) {
            $invalidProperties[] = "invalid value for 'from', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['size']) && ($this->container['size'] > 500)) {
            $invalidProperties[] = "invalid value for 'size', must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['size']) && ($this->container['size'] < 0)) {
            $invalidProperties[] = "invalid value for 'size', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets entity_types
     *
     * @return string[]
     */
    public function getEntityTypes(): array
    {
        return $this->container['entity_types'];
    }

    /**
     * Sets entity_types
     *
     * @param string[] $entity_types One or more types of resources expected in the response. Currently only `driveItem` is supported.
     *
     * @return $this
     */
    public function setEntityTypes(array $entity_types): static
    {
        if (is_null($entity_types)) {
            throw new InvalidArgumentException('non-nullable entity_types cannot be null');
        }
        $allowedValues = $this->getEntityTypesAllowableValues();
        if (array_diff($entity_types, $allowedValues)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value for 'entity_types', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }


        if ((count($entity_types) < 1)) {
            throw new InvalidArgumentException('invalid length for $entity_types when calling SearchRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['entity_types'] = $entity_types;

        return $this;
    }

    /**
     * Gets query
     *
     * @return \OpenAPI\Client\Model\SearchQuery
     */
    public function getQuery(): \OpenAPI\Client\Model\SearchQuery
    {
        return $this->container['query'];
    }

    /**
     * Sets query
     *
     * @param \OpenAPI\Client\Model\SearchQuery $query query
     *
     * @return $this
     */
    public function setQuery(\OpenAPI\Client\Model\SearchQuery $query): static
    {
        if (is_null($query)) {
            throw new InvalidArgumentException('non-nullable query cannot be null');
        }
        $this->container['query'] = $query;

        return $this;
    }

    /**
     * Gets from
     *
     * @return int|null
     */
    public function getFrom(): ?int
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param int|null $from Specifies the offset for the search results. Offset 0 returns the very first result. Used together with the `size` property for pagination.
     *
     * @return $this
     */
    public function setFrom(?int $from): static
    {
        if (is_null($from)) {
            throw new InvalidArgumentException('non-nullable from cannot be null');
        }

        if (($from < 0)) {
            throw new InvalidArgumentException('invalid value for $from when calling SearchRequest., must be bigger than or equal to 0.');
        }

        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int|null
     */
    public function getSize(): ?int
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int|null $size The size of the page to be retrieved. The maximum value is 500. Set to 0 to return only aggregations without any hits.
     *
     * @return $this
     */
    public function setSize(?int $size): static
    {
        if (is_null($size)) {
            throw new InvalidArgumentException('non-nullable size cannot be null');
        }

        if (($size > 500)) {
            throw new InvalidArgumentException('invalid value for $size when calling SearchRequest., must be smaller than or equal to 500.');
        }
        if (($size < 0)) {
            throw new InvalidArgumentException('invalid value for $size when calling SearchRequest., must be bigger than or equal to 0.');
        }

        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets aggregations
     *
     * @return \OpenAPI\Client\Model\AggregationOption[]|null
     */
    public function getAggregations(): ?array
    {
        return $this->container['aggregations'];
    }

    /**
     * Sets aggregations
     *
     * @param \OpenAPI\Client\Model\AggregationOption[]|null $aggregations Specifies aggregations (also known as refiners or facets) to be returned alongside the search results. Optional.
     *
     * @return $this
     */
    public function setAggregations(?array $aggregations): static
    {
        if (is_null($aggregations)) {
            throw new InvalidArgumentException('non-nullable aggregations cannot be null');
        }
        $this->container['aggregations'] = $aggregations;

        return $this;
    }

    /**
     * Gets aggregation_filters
     *
     * @return string[]|null
     */
    public function getAggregationFilters(): ?array
    {
        return $this->container['aggregation_filters'];
    }

    /**
     * Sets aggregation_filters
     *
     * @param string[]|null $aggregation_filters Contains one or more filters to narrow search results to specific buckets of a prior aggregation. Build each filter from the response of a prior search that aggregated on the same field: take the `aggregationFilterToken` of the wanted `searchBucket` and combine it with the field as `{field}:{aggregationFilterToken}`, e.g. `audio.artist:\"ǂǂ5361786f6e\"` for a terms bucket or `audio.year:range(1980, 1990)` for a range bucket. Several buckets of the same field are combined with `{field}:or({aggregationFilterToken},{aggregationFilterToken})`. Whitespace after the commas of `range(...)` and `or(...)` is optional.  Multiple filters can be provided as separate array items. This results in a logical AND between the filters. Filters that are not built from server-issued tokens are rejected with `invalidRequest`.
     *
     * @return $this
     */
    public function setAggregationFilters(?array $aggregation_filters): static
    {
        if (is_null($aggregation_filters)) {
            throw new InvalidArgumentException('non-nullable aggregation_filters cannot be null');
        }
        $this->container['aggregation_filters'] = $aggregation_filters;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


